# Generated by Django 5.2.14 on 2026-05-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="proposed_team",
            field=models.ManyToManyField(
                blank=True, related_name="proposed_for", to="game.player"
            ),
        ),
    ]
