# Generated by Django 5.2.14 on 2026-05-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_gameroom_proposed_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="has_voted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="vote_approve",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
