# Generated by Django 5.2.14 on 2026-05-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_player_has_voted_player_vote_approve"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="score_evil",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gameroom",
            name="score_good",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="has_quest_voted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="quest_vote_success",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
