# Generated by Django 5.2.14 on 2026-05-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_gameroom_score_evil_gameroom_score_good_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="last_vote",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
