# Generated by Django 5.2.14 on 2026-05-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_player_last_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="fails_count",
            field=models.IntegerField(default=0),
        ),
    ]
