# Generated by Django 5.2.14 on 2026-05-11 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_mission_fails_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                (
                    "approves",
                    models.ManyToManyField(
                        related_name="history_approves", to="game.player"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_proposals",
                        to="game.gameroom",
                    ),
                ),
                (
                    "rejects",
                    models.ManyToManyField(
                        related_name="history_rejects", to="game.player"
                    ),
                ),
                (
                    "team",
                    models.ManyToManyField(
                        related_name="history_team", to="game.player"
                    ),
                ),
            ],
        ),
    ]
