# Generated by Django 5.2.14 on 2026-05-11 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_teamproposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamproposal",
            name="leader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history_led",
                to="game.player",
            ),
        ),
    ]
