# Generated by Django 5.2.14 on 2026-05-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_teamproposal_leader"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="victory_reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
