# Generated by Django 5.2.14 on 2026-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_gameroom_victory_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="assassination_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
