# Generated by Django 5.2.14 on 2026-05-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_gameroom_assassination_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
