# Generated by Django 5.2.14 on 2026-05-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_spectator"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="allow_spectator_spoilers",
            field=models.BooleanField(default=False),
        ),
    ]
