# Generated by Django 5.2.14 on 2026-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_gameroom_allow_spectator_spoilers"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="pending_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
