# Generated by Django 5.2.14 on 2026-05-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_player_pending_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="current_lady_holder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_lady_room",
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="gameroom",
            name="use_lady_of_the_lake",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="lady_target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lady_received_from",
                to="game.player",
            ),
        ),
    ]
