# Generated by Django 5.2.14 on 2026-05-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_gameroom_current_lady_holder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
