# Generated by Django 5.2.14 on 2026-05-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0016_gameroom_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="rematch_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
