# Generated by Django 5.2.14 on 2026-05-25 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_gameroom_rematch_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_test_account", models.BooleanField(default=False)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Custom name shown in lobbies and leaderboards.",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "favorite_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Merlin", "Merlin"),
                            ("Percival", "Percival"),
                            ("Lover", "Lover"),
                            ("Loyal Servant of Arthur", "Loyal Servant of Arthur"),
                            ("Morgana", "Morgana"),
                            ("Mordred", "Mordred"),
                            ("Assassin", "Assassin"),
                            ("Minion of Mordred", "Minion of Mordred"),
                            ("Oberon", "Oberon"),
                        ],
                        help_text="Your preferred Avalon role to display on your stats page.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
